# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: IrfanSkiljan.IrfanView.x86
PackageVersion: '4.66'
PackageLocale: en-US
Publisher: Irfan Skiljan
PublisherUrl: https://www.irfanview.com
PublisherSupportUrl: https://irfanview-forum.de
PrivacyUrl: https://www.irfanview.com/privacy_policy.htm
Author: Irfan Skiljan
PackageName: IrfanView (x86)
PackageUrl: https://www.irfanview.com
License: Proprietary, free for non-commercial use
LicenseUrl: https://www.irfanview.com/eula.htm
Copyright: Copyright (C) 2021 by Irfan Skiljan, Wiener Neustadt, Austria.
CopyrightUrl: https://www.irfanview.com/eula.htm
ShortDescription: Fast and compact image viewer and converter
Description: |-
  IrfanView is an image viewer, editor, organiser and converter program for Microsoft Windows.
  It can also play video and audio files, and has some image creation and painting capabilities.
  IrfanView is free for non-commercial use; commercial use requires paid registration.
  It is noted for its small size, speed, ease of use, and ability to handle a wide variety of graphic file formats.
  Note: The 32-bit version and 64-bit version currently support different feature-sets and can be installed side-by-side 
  For a comparison between the 32/64-bit versions, see: https://www.irfanview.com/64bit.htm
Moniker: irfanview
Tags:
- graphic-editor
- graphic-viewer
- image
- image-viewer
- photo
- picture
ManifestType: defaultLocale
ManifestVersion: 1.5.0
